name: Benchmark on Demand

on:
  pull_request_review_comment:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - if: contains(github.event.comment.body, "!!!benchmark")
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Benchmark Feature Phases
        run: ./gradlew run -q --args="--Xbenchmark-phases" > feature-phases.csv
      - name: Benchmark Feature Throughput
        run: ./gradlew run -q --args="--Xbenchmark-throughput" > feature-throughput.csv
        
