name: Community Build

on: [workflow_call]

permissions:
  contents: read

jobs:
  # Build the JAR once for all the community builds
  build-jar:
    runs-on: ubuntu-latest
    steps:
      - name: Check out branch
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build Flix JAR
        run: ./gradlew jar
      - name: Upload Flix JAR
        uses: actions/upload-artifact@v3
        with:
          name: flix-jar
          path: build/libs/flix.jar

  # Spawn a separate job per community build
  community-build:
    needs: build-jar
    strategy:
      # collect all the failures
      fail-fast: false
      # run them one at a time
      max-parallel: 1
      matrix:
        repo:
          - "JonathanStarup/Flix-ANSI-Terminal"
          - "flix/museum"
          - "jaschdoc/flix-parsers"
          - "mlutze/fcwg"
          - "mlutze/flix-json"
          - "mlutze/flixball"
          - "stephentetley/charset-locale"
          - "stephentetley/flix-either"
          - "stephentetley/flix-htmldoc"
          - "stephentetley/flix-pretty"
    runs-on: ubuntu-latest
    steps:
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Check out project head
        uses: actions/checkout@v2
        with:
          repository: ${{ matrix.repo }}
      - name: Download the community build JAR
        uses: dawidd6/action-download-artifact@v2
        with:
          name: flix-jar
          workflow: build-jar.yaml
          workflow_conclusion: success
      - name: Build community project
        timeout-minutes: 10
        run: |
          # Build the project.
          java -jar flix.jar build --github-key ${{ github.token }}
