on: [pull_request]

jobs:
  community-build:
  
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build jar
        run: ./gradlew jar
      - name: Build community project
        run: mkdir tmp && cd tmp && java -jar ../build/libs/flix.jar init && java -jar ../build/libs/flix.jar install mlutze/flix-json && java.jar ../build/libs/flix.jar build
