name: Community Build

on: [workflow_call]

permissions:
  contents: read

jobs:
  # NB: depends on having a valid flix.jar file

  # Spawn a separate job per community build
  community-build:
    strategy:
      # collect all the failures
      fail-fast: false
      # run them one at a time
      max-parallel: 1
      matrix:
        repo:
          - "JonathanStarup/Flix-ANSI-Terminal"
          - "flix/museum"
          - "jaschdoc/flix-parsers"
          - "mlutze/fcwg"
          - "mlutze/flix-json"
          - "mlutze/flixball"
          - "stephentetley/charset-locale"
          - "stephentetley/flix-either"
          - "stephentetley/flix-htmldoc"
          - "stephentetley/flix-pretty"
    runs-on: ubuntu-latest
    steps:
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Check out project head
        uses: actions/checkout@v2
        with:
          repository: ${{ matrix.repo }}
      - name: Download Flix JAR
        uses: actions/download-artifact@v3
        with:
          name: flix-jar
      - name: Build community project
        timeout-minutes: 10
        run: |
          # Build the project.
          java -jar flix.jar build --github-key ${{ github.token }}
