name: Format Tests

on: [pull_request, merge_group]

permissions:
  contents: read

# Cancel previous runs if the PR is updated
concurrency:
  cancel-in-progress: true
  group: format-${{ github.ref }}

jobs:
  # Build the JAR once for all the community builds
  build-jar:
    runs-on: ubuntu-latest
    steps:
      - name: Check out branch
        uses: actions/checkout@v4
      - name: Install Coursier
        run: |
          curl -fL "https://github.com/coursier/launchers/raw/master/cs-x86_64-pc-linux.gz" | gzip -d > cs
          chmod +x cs
          ./cs setup --yes
          cs install scalafmt
      - name: Run formatter
        run: scalafmt --test --non-interactive

