name: JAR on Demand

on:
  issue_comment:
    types: [created]

jobs:
  handle-request:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '!!!jar')
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Download the community build JAR
        uses: dawidd6/action-download-artifact@v2
        with:
          name: flix-jar
          # Optional, workflow file name or ID
          # If not specified, will be inferred from run_id (if run_id is specified), or will be the current workflow
          workflow: community-build.yaml
          # Optional, the status or conclusion of a completed workflow to search for
          # Can be one of a workflow conclusion:
          #   "failure", "success", "neutral", "cancelled", "skipped", "timed_out", "action_required"
          # Or a workflow status:
          #   "completed", "in_progress", "queued"
          # Use the empty string ("") to ignore status or conclusion in the search
          workflow_conclusion: success

      - name: Upload JAR
        uses: actions/upload-artifact@v1
        with:
          name: JAR
          path: build/libs/flix.jar
      - name: Comment JAR link
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: >
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "The JAR is available [HERE](" + "https://github.com/" + context.repo.owner + "/" + context.repo.repo + "/actions/runs/" + context.runId + ")."
            })
